### ISSUE TITLE
questions about rir_dataset in fullband_train.toml

### ISSUE THREAD

**Issue by realkris** [haoxiangsnr/FullSubNet#10]
I am really interested in this project, but I am a little confused about the rir_dataset, and I want to make clear about what rir_dataset is. Is it compatitable with any dataset elsewhere or is there a project's official dataset?

这个项目很有意思，但是那个rir_dataset在原始的DNS数据集里没有，我注意到网上有一些，但我不确定能不能用？
或者您当时跑训练时用的rir数据集方便参考一下？
感谢！

**Comment by haoxiangsnr** [comment]
Yes,  it's compatible with other RIRs. You may be able to refer to the following information:

1. https://www.eng.biu.ac.il/~gannot/RIR_DATABASE/
2. Simulation using the image source method (https://github.com/ehabets/RIR-Generator)
