### ISSUE TITLE
您好，请教下关于overlapped_chunk()函数

### ISSUE THREAD

**Issue by ghost** [haoxiangsnr/FullSubNet#14]
您好，能问下https://github.com/haoxiangsnr/FullSubNet/blob/main/recipes/dns_interspeech_2020/inferencer.py#L130 noisy传入的大小嘛，以及num_mics=8的含义。

**Comment by haoxiangsnr** [comment]
Hi,

Sorry for my late reply as I missed this issue. 

These codes are for multi-channel speech enhancement. I will release a multi-channel version in near future.

Thanks for your attention.
