### ISSUE TITLE
The batch size for the validation stage must be one

### ISSUE THREAD

**Issue by lzc16** [haoxiangsnr/FullSubNet#17]
Hi Hao Xiang

I can't run the demo due to the limit that gpu usage must be over 20 percentage. Therefore, I found the validation set the batchsize 

must be one. Can I change the batchsize in validation?

Hope your reply!

**Comment by haoxiangsnr** [comment]
Hi,

Sorry, since samples have different lengths, you cannot add the `batch_size` in the validation stage.
