### ISSUE TITLE
reverberat data 

### ISSUE THREAD

**Issue by victorVoice** [haoxiangsnr/FullSubNet#20]
When i look into the code in generate training data, the reverberation step convolve the rir signal with the clean signal. Then the reverberated signal act as clean signal to train the network.  Is there something wrong or i misunderstanding the code.

**Comment by haoxiangsnr** [comment]
Hi,

We only conduct noise reduction, not dereverberation. 
If you want to conduct speech dereverberation, you can try to change the training target to the original clean speech.
