### ISSUE TITLE
Not an issue, but I wanted to show you some impressive results...

### ISSUE THREAD

**Issue by sjscotti** [haoxiangsnr/FullSubNet#21]
Greetings!
I have been helping restore an old (1980) recording of a recording of an interview with an elderly person relaying stories of the early history of the Baha'i Faith in the U.S..  I have surveyed and tried a number of machine learning methods to denoise and enhance the recording.  I just finished processing with your FullSubNet today, and it far surpassed the other ones I tried out in removing the recording noise to make the voice easier to understand.  Enclosed is a graphic of the comparison of the frequency spectograms of the 3 files where the top one is the original recording, the middle is the result of using another method (that was dozens of times slower than yours and principally dealt with white noise) and at the bottom is the result of FullSubNet using your pretrained checkpoint.  The reduction in noise going from the original recording to what your method produced was astonishing!  I can check to see if the archivist would allow me to provide the recordings (so if you are interested in getting them, please let me know).  Thanks so much for making the code available here!
Regards
-Steve

![compare_orig_n2n_fullsubnet](https://user-images.githubusercontent.com/44651388/120113541-f5c3fb80-c148-11eb-89aa-73a87bef30b9.JPG)

**Comment by haoxiangsnr** [comment]
Thank you for your attention. I am glad to hear it.

If you have any questions, please feel free to contact me.

**Comment by faranaziz** [comment]
> Greetings!
> I have been helping restore an old (1980) recording of a recording of an interview with an elderly person relaying stories of the early history of the Baha'i Faith in the U.S.. I have surveyed and tried a number of machine learning methods to denoise and enhance the recording. I just finished processing with your FullSubNet today, and it far surpassed the other ones I tried out in removing the recording noise to make the voice easier to understand. Enclosed is a graphic of the comparison of the frequency spectograms of the 3 files where the top one is the original recording, the middle is the result of using another method (that was dozens of times slower than yours and principally dealt with white noise) and at the bottom is the result of FullSubNet using your pretrained checkpoint. The reduction in noise going from the original recording to what your method produced was astonishing! I can check to see if the archivist would allow me to provide the recordings (so if you are interested in getting them, please let me know). Thanks so much for making the code available here!
> Regards
> -Steve
> 
> ![compare_orig_n2n_fullsubnet](https://user-images.githubusercontent.com/44651388/120113541-f5c3fb80-c148-11eb-89aa-73a87bef30b9.JPG)

Hello,
How did you run inference on a single WAV file? Can you share the code? 
Thanks you.
