### ISSUE TITLE
# of Epochs for training a FullBand baseline model

### ISSUE THREAD

**Issue by kadir-gunel** [haoxiangsnr/FullSubNet#22]
Hello, 

My question is about the training. I am just trying to replicate the results with the DNS challange dataset. The number of epochs for the fullband_baseline.toml file is set to 9999 which seems to be a "little" high :) Could you please shed some light on it ? Is this the default value ? 

Thank you for sharing your work. 

B.R.

**Comment by haoxiangsnr** [comment]
Hi, Kadir,

Sorry, I’m preparing to graduate recently and I haven’t had time to reply to you.

"9999" is the upper limit number of the training epoch. I think you should use TensorBoard to check whether the model converges during the training.

Thank you for your attention.

**Comment by kadir-gunel** [comment]
Ok. Thank you. 

Good luck with the graduation ! Hope everything goes well :)
