### ISSUE TITLE
Any plans about releasing the pretrained models？

### ISSUE THREAD

**Issue by 121898** [haoxiangsnr/FullSubNet#3]
First, thanks for the open-source implementation. I saw that the pretrained model is on your TO-DO list in the baseline readme. Do you have any plans for the releasing schedule?
Thanks a lot!

**Comment by haoxiangsnr** [comment]
The pre-trained model is in here: https://github.com/haoxiangsnr/FullSubNet/releases

I will update the docs, maybe this weekend? 😃

**Comment by haoxiangsnr** [comment]
Hi, Recently, I have been doing a major refactoring of this project. The new code and documentation will be released in about March.

Thanks for your attention.

**Comment by eric574** [comment]
@haoxiangsnr  Hi, it's already April and there still isn't any documentation for the pretrained model. How do we go about using the pickled file? Thanks!
