### ISSUE TITLE
Questions about the training process

### ISSUE THREAD

**Issue by ahikaml** [haoxiangsnr/FullSubNet#5]
Very interesting project. Thank you for sharing.

I have a quastion - what are the text files noise.txt, rir.txt and clean_0.6.txt? 
Are they part of the original dataset or dedicated files that you've created for the training? 

Another qaustion - is it possible to run it on Windows run without the "dist" feature (using a single GPU)? 
(I mean after commecting all parts related to the 'dist')

**Comment by vvasily** [comment]
I think you should create them manually for DNS-Challenge/datasets/clean and DNS-Challenge/datasets/noise dirs. The noise.txt, clean_0.6.txt contains the list of files (with absolute path) from these dirs. 
rir.txt is the file with RIR (Room Impulse Responses), you can download it separately somewhere. 
Dataset wav is : clean + noise + RIR. If you don't want to use RIR just leave rir.txt empty and set reverb_proportion to 0.0 in *.toml

**Comment by haoxiangsnr** [comment]
Sorry, I have not had time to deal with this issue recently. You could try it according to the @vvasily 's explanation.

I think this issue might be solved. If you any questions, please feel free to open a new issue.
