### ISSUE TITLE
[Question] The real-time speech enhance is poor, Need help!

### ISSUE THREAD

**Issue by Kayden-Wang** [haoxiangsnr/FullSubNet#55]
At present, I have completed the modification of cumulative_laplace_norm, and then sent it to the network in batches through Stft for streaming inference, and obtained the Hidden state and cell state of the network. But the results are poor. I looked at the previous issue, you said that you need to replace LSTM with LSTMCell, **what is the difference between the two? Why do you convert it?** 
Pictures are as follow:
* **Fullwav_load:**

![image](https://user-images.githubusercontent.com/112678477/188058552-13113bd7-83f8-414c-9adb-1f20d9d6b4eb.png)

* **Stream_load:**

![image](https://user-images.githubusercontent.com/112678477/188058389-9b288a18-c9e5-4397-bc71-7a6d1e6ed3be.png)

Metrics: (My experiment)

<html>
<body>
<!DOCTYPE html>

... | NB_PESQ | WB_PESQ | SI_SDR | STOI
-- | -- | -- | -- | --
FullSubNet-cum\| Epoch 130 | 3.364 | 2.861 | 17.65 | 96.25
FullSubNet-cum-stream \| | 3.155 | 2.466 | 14.77 | 94.30

</body>
</html>

**Comment by haoxiangsnr** [comment]
Hi @Kayden-Wang,

Thanks for your try.

1. what is the difference between the two? 
The `LSTMCell` module is a cell for each time step. The input is the 

The `LSTM` can be seen as a for-loop version of the `LSTMCell`.

3. Why do you convert it?

If you want to use it in a real product, you may write the code like:

```python
for frame in range(time_frames):
    
```



Could you show me your code snippets?

**Comment by Kayden-Wang** [comment]
Problem solved, thanks a lot! @haoxiangsnr , Closed

**Comment by bhpugongying** [comment]
@Kayden-Wang can you share the code of real-time speech enhance? Thank you!
