### ISSUE TITLE
Training dataset bug

### ISSUE THREAD

**Issue by Azatiussss** [haoxiangsnr/FullSubNet#56]
Looks like a bug
https://github.com/haoxiangsnr/FullSubNet/blob/38bb6e64b4bebc377e1ba84911851aae51b6cc37/recipes/dns_interspeech_2020/dataset_train.py#L214-L217

**Comment by haoxiangsnr** [comment]
Hi, @Azatiussss ,

Thanks for your feedback. I'm sorry for that. It seems like a bug introduced by the [last commit](https://github.com/haoxiangsnr/FullSubNet/blob/a4c1a4fc042dd15f1cb3bfd2e215086c13bd82e7/recipes/dns_interspeech_2020/dataset_train.py). I have fixed it. 

Thanks again.
